In [ ]:
## import the important libraries
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
import sys
import math
from copy import deepcopy
from sklearn import neighbors


In [ ]:
## download the training and testing files
corrected = pd.read_csv("/content/corrected.gz", compression="gzip",header=None)
dftotal = pd.read_csv("/content/kddcup.data.gz", compression="gzip", header=None)
df = pd.read_csv("/content/kddcup.data_10_percent.gz", compression="gzip", header=None)

In [ ]:
## concatenate all the data (training and testing) to be encoeded and mapped to the same code
dfmerge = pd.concat([dftotal,corrected,df],ignore_index=True)
dfmerge

0    1     2   3    4      5   6   7   8   9   ...   32   33   34  \
0         0  tcp  http  SF  215  45076   0   0   0   0  ...    0  0.0  0.0   
1         0  tcp  http  SF  162   4528   0   0   0   0  ...    1  1.0  0.0   
2         0  tcp  http  SF  236   1228   0   0   0   0  ...    2  1.0  0.0   
3         0  tcp  http  SF  233   2032   0   0   0   0  ...    3  1.0  0.0   
4         0  tcp  http  SF  239    486   0   0   0   0  ...    4  1.0  0.0   
...      ..  ...   ...  ..  ...    ...  ..  ..  ..  ..  ...  ...  ...  ...   
5703476   0  tcp  http  SF  310   1881   0   0   0   0  ...  255  1.0  0.0   
5703477   0  tcp  http  SF  282   2286   0   0   0   0  ...  255  1.0  0.0   
5703478   0  tcp  http  SF  203   1200   0   0   0   0  ...  255  1.0  0.0   
5703479   0  tcp  http  SF  291   1200   0   0   0   0  ...  255  1.0  0.0   
5703480   0  tcp  http  SF  219   1234   0   0   0   0  ...  255  1.0  0.0   

           35    36    37    38   39   40       41  
0        0.00  0.00  0.00  0.00  0.0  0.0  normal.  
1        1.00  0.00  0.00  0.00  0.0  0.0  normal.  
2        0.50  0.00  0.00  0.00  0.0  0.0  normal.  
3        0.33  0.00  0.00  0.00  0.0  0.0  normal.  
4        0.25  0.00  0.00  0.00  0.0  0.0  normal.  
...       ...   ...   ...   ...  ...  ...      ...  
5703476  0.01  0.05  0.00  0.01  0.0  0.0  normal.  
5703477  0.17  0.05  0.00  0.01  0.0  0.0  normal.  
5703478  0.06  0.05  0.06  0.01  0.0  0.0  normal.  
5703479  0.04  0.05  0.04  0.01  0.0  0.0  normal.  
5703480  0.17  0.05  0.00  0.01  0.0  0.0  normal.  

[5703481 rows x 42 columns]

In [ ]:
# converting categorical data to numeric data
dfmergenew = dfmerge
## convert the columns 1,2,3,41 which include categorical data
for i in[1,2,3,41]: 
  lenew = LabelEncoder() 
  ## Using .fit_transform function to fit label encoder and return encoded label
  labelnew = lenew.fit_transform(dfmergenew[i])
  ## replacing the categorical data column with the equivalent numerical data
  dfmergenew[i] = labelnew
## split the testing data (10% and total data) and the testing data again

##-- the total data
xtrain_total = dfmergenew.iloc[0:4898431, 0:41] # features
ytrain_total= pd.DataFrame(dfmergenew.iloc[0:4898431, 41]) # label

##-- the test data
xtest = dfmergenew.iloc[4898431:5209460, 0:41] # features
ytest = pd.DataFrame(dfmergenew.iloc[4898431:5209460, 41]) # label

##-- 10% data
xtrain = dfmergenew.iloc[5209460:, 0:41] # features
ytrain = pd.DataFrame(dfmergenew.iloc[5209460:, 41]) # label
dfmergenew

0   1   2   3    4      5   6   7   8   9   ...   32   33   34    35  \
0         0   1  24   9  215  45076   0   0   0   0  ...    0  0.0  0.0  0.00   
1         0   1  24   9  162   4528   0   0   0   0  ...    1  1.0  0.0  1.00   
2         0   1  24   9  236   1228   0   0   0   0  ...    2  1.0  0.0  0.50   
3         0   1  24   9  233   2032   0   0   0   0  ...    3  1.0  0.0  0.33   
4         0   1  24   9  239    486   0   0   0   0  ...    4  1.0  0.0  0.25   
...      ..  ..  ..  ..  ...    ...  ..  ..  ..  ..  ...  ...  ...  ...   ...   
5703476   0   1  24   9  310   1881   0   0   0   0  ...  255  1.0  0.0  0.01   
5703477   0   1  24   9  282   2286   0   0   0   0  ...  255  1.0  0.0  0.17   
5703478   0   1  24   9  203   1200   0   0   0   0  ...  255  1.0  0.0  0.06   
5703479   0   1  24   9  291   1200   0   0   0   0  ...  255  1.0  0.0  0.04   
5703480   0   1  24   9  219   1234   0   0   0   0  ...  255  1.0  0.0  0.17   

           36    37    38   39   40  41  
0        0.00  0.00  0.00  0.0  0.0  16  
1        0.00  0.00  0.00  0.0  0.0  16  
2        0.00  0.00  0.00  0.0  0.0  16  
3        0.00  0.00  0.00  0.0  0.0  16  
4        0.00  0.00  0.00  0.0  0.0  16  
...       ...   ...   ...  ...  ...  ..  
5703476  0.05  0.00  0.01  0.0  0.0  16  
5703477  0.05  0.00  0.01  0.0  0.0  16  
5703478  0.05  0.06  0.01  0.0  0.0  16  
5703479  0.05  0.04  0.01  0.0  0.0  16  
5703480  0.05  0.00  0.01  0.0  0.0  16  

[5703481 rows x 42 columns]

In [ ]:
# removing labels in test that the model wasn't trained on
print(ytest[41].unique())
labels = ytrain[41].unique()
print(labels)
x_test=xtest.to_numpy()
y_test=ytest.to_numpy()
for i in range(len(y_test)-1,-1,-1):
  if y_test[i,0]  not in labels:
     y_test= np.delete(y_test,i,0)
     x_test=np.delete(x_test,i,0)
print(ytest[41].unique())

[16 28 13 37 27  7 12 38 26  4 24  2 20 19  0 18 33 35 17 25 39 11 21 22
 15 23 14  9  6  1  5 36 10  3 32  8 31 29]
[16  2  9 17 14 27  4 19 32 20  7  8  3  1  6 25 18 15 12 35 34 30 23]
[16 28 13 37 27  7 12 38 26  4 24  2 20 19  0 18 33 35 17 25 39 11 21 22
 15 23 14  9  6  1  5 36 10  3 32  8 31 29]


In [ ]:
print(np.unique(y_test))
print()
print(np.sort(labels))

[ 1  2  3  4  6  7  8  9 12 14 15 16 17 18 19 20 23 25 27 32 35]

[ 1  2  3  4  6  7  8  9 12 14 15 16 17 18 19 20 23 25 27 30 32 34 35]


In [ ]:
def kmeans(data,no_clusters=3,max_iteration=100,init_seeds=None):
  t=0
  repeat = 1
  rows=data.shape[0]
  columns=data.shape[1]
  nu_clusters=no_clusters ## number of clusters
  max_iter=max_iteration  ## maximum number of iterations
  distance=np.zeros((rows,nu_clusters)) ## a distance matrix with dimensions data size x number of clusters
  clusters=np.zeros(rows) ## an array to store the equivalent cluster number of each node


  ## if there is no initial centoids then pick random centroids 
  ## else assign them the old centroids to be the first centroids of the cluster
  if (init_seeds is None):
    old_centroids = data.sample(n=nu_clusters)
  else:
    old_centroids=init_seeds

  unique = old_centroids.drop_duplicates().shape[0]
  boolean = old_centroids.duplicated().any()
  ## check that all the centroids are unique and there are no duplicates
  while(boolean):
    old_centroids = old_centroids.drop_duplicates()
    difference = nu_clusters - unique
    old_centroids2 = data.sample(n=difference)
    old_centroids = pd.concat([old_centroids,old_centroids2],ignore_index=True)
    unique = old_centroids.drop_duplicates().shape[0]
    boolean = old_centroids.duplicated().any()
  new_centroids=np.zeros(old_centroids.shape)
  while (t<max_iteration):
    t=t+1
    #old_centroids = new_centroids
    # measure the distance of each row to every cluster
    for i in range (nu_clusters):
      distance[:,i]=np.linalg.norm(data-old_centroids.iloc[i,:],axis=1)
    # assign data to closest centroid
    clusters=np.argmin(distance, axis=1)
    # update centroid
    for i in range (nu_clusters):
      old_centroids.iloc[i,:]=np.mean(data[clusters==i],axis=0)
      # new_centroids[i,:]=np.mean(data[clusters==i],axis=0)
    # if new_centroids == old_centroids:
    #   break
    # old_centroids = deepcopy(new_centroids)
  return old_centroids,clusters

####Evaluation

In [ ]:
def evaluate(clusters,new_centroids,testx,testy): 
    ## cluster the testing set
    rows=testx.shape[0]
    nu_clusters = len(np.unique(clusters))
    distance=np.zeros((rows,nu_clusters))
    test_clusters=np.zeros(rows)
    new_centroids = new_centroids.to_numpy()
    ## calculate the distance between the test data and the centroids from the kmeans
    for i in range (nu_clusters):
        distance[:,i]=np.linalg.norm(testx-new_centroids[i,:],axis=1)
    ## assign data to closest centroid
    test_clusters=np.argmin(distance, axis=1)
    print("Unique test cluster:")
    print(np.unique(test_clusters))
    print(test_clusters)


    d=testy  ##truth array
    t=test_clusters ##output array

    t_unique,t_count = np.unique(t,return_counts=True)
    d_unique,d_count = np.unique(d,return_counts=True)
    

    clus_row = nu_clusters
    clus_col = np.max(testy)+1
    print("@K = ",clus_row)
    count = np.zeros([clus_row,clus_col])
    ## count the number of different data in the clusters
    for i in range(len(t)):
       count[t[i]][d[i]] = count[t[i]][d[i]] +1    ## rows: output clusters (k), columns: testing clusters (40)
    row_sum= np.sum(count,axis=1) ## the sum of data in each cluster
    column_sum= np.sum(count,axis=0) ## the sum of data in different group of the test data
    total_row_sum = np.sum(row_sum) ## the total number of test data

    htc = np.zeros([1,clus_row])
    print("The count array size:", count.shape)


    ##Conditional Entropy
    print("------------------------------------------------------------------------------")
    print("Conditional Entropy")
    for i in range(clus_row):
      for j in range(clus_col):
        ## calculate H(T/Ci)
        if (count[i][j]):
          htc[0][i] = htc[0][i] - ( count[i][j]/row_sum[i] * math.log(count[i][j]/row_sum[i],10) )
    print(htc)
    htc_total = 0
    for i in range(clus_row):
      ## calculate the total entropy
      htc_total = htc_total + ( row_sum[i]/total_row_sum * htc[0][i] )
    print("Condition Entropy = ", htc_total)



    ##Precision and Recall
    print("------------------------------------------------------------------------------")
    print("Precision and Recall")
    max_element = np.max(count,axis=1) ## choose the majority element
    index_sum = np.zeros([1,len(max_element)])
    ## find the index of the major element in each cluster
    for i in range(len(max_element)):
      temp = np.argwhere(count == max_element[i])
      for j in temp:
        if (j[0] == i):
          index_sum[0][i] = column_sum[j[1]]

    prec = np.zeros([1,len(max_element)])
    total_prec=0 
    total_rec=0 
    rec = np.zeros([1,len(max_element)])

    for i in range(len(max_element)):
      ## calculate the precision of the cluster and the total precision
      prec[0][i] = max_element[i]/row_sum[i]
      prec[np.isnan(prec)] = 0
      total_prec = total_prec + (row_sum[i]/rows)*prec[0][i]
      ## calculate the recall of the cluster and the total recall
      rec[0][i] = max_element[i]/index_sum[0][i]      
      total_rec = total_rec + (row_sum[i]/rows)*rec[0][i]

    print("Precision: ")
    print(prec)
    print("Total Precision = ",total_prec)
  
    print("Recall:")
    print(rec)
    print("Total Recall = ",total_rec)
    

    ##F-score
    print("------------------------------------------------------------------------------")
    print("F-score")
    f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
    print("F-cluster: ")
    f_cluster[np.isnan(f_cluster)] = 0
    print(f_cluster)
    f_measure = np.sum(f_cluster,axis=1) * 1/clus_row
    print("F-score: ")
    f_measure[np.isnan(f_measure)] = 0
    print(f_measure)  

###Kmean 

In [ ]:
k=[7,15,23,31,45]
#k=[7]
## loop on different number of clusters and apply the kmeans then the evaluation
for i in k:
  new_centroids,clusters = kmeans(xtrain,i)
  print("clusters at k=",i,":")
  print(clusters)
  print(len(np.unique(clusters)))
  evaluate(clusters,new_centroids,x_test,y_test)

clusters at k= 7 :
[6 6 6 ... 6 6 6]
7
Unique test cluster:
[0 1 3 4 5 6]
[6 6 6 ... 6 6 6]
@K =  7
The count array size: (7, 36)
------------------------------------------------------------------------------
Conditional Entropy
[[0.35134321 0.         0.         0.10759682 0.         0.
  0.48073285]]
Condition Entropy =  0.4798976116176942
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[0.63774024 1.         0.         0.94594595 1.         1.
  0.56480076]]
Total Precision =  0.5653027711255558
Recall:
[[9.97267760e-01 1.65035565e-05 0.00000000e+00 5.77624478e-04
  6.60142261e-05 1.98042678e-04 1.00000000e+00]]
Total Recall =  0.9997992910446379
------------------------------------------------------------------------------
F-score
F-cluster: 
[[7.77975133e-01 3.30065683e-05 0.00000000e+00 1.15454396e-03
  1.32019737e-04 3.96006930e-04 7.21882011e-01]]
F-score: 
[0.21451039]


<ipython-input-10-1391b4c23467>:76: RuntimeWarning: invalid value encountered in double_scalars
  prec[0][i] = max_element[i]/row_sum[i]
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: divide by zero encountered in true_divide
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: invalid value encountered in multiply
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))


clusters at k= 15 :
[11 12 12 ... 12 12 12]
15
Unique test cluster:
[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14]
[12 12 12 ... 12 12 12]
@K =  15
The count array size: (15, 36)
------------------------------------------------------------------------------
Conditional Entropy
[[0.07293722 0.35023688 0.01011893 0.         0.         0.
  0.03904746 0.         0.06188951 0.         0.         0.00681146
  0.4279572  0.         0.00918364]]
Condition Entropy =  0.1912094637424833
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[0.96       0.63848397 0.99686717 1.         1.         1.
  0.98272278 1.         0.96774194 0.         1.         0.99809039
  0.50973758 1.         0.996875  ]]
Total Precision =  0.797085186452275
Recall:
[[3.96085356e-04 9.97267760e-01 2.62571584e-02 9.90213391e-05
  6.60142261e-05 2.47553348e-04 9.99695291e-01 1.65035565e-05
  4.95106695e-04 0.00000000e+00 1.98042678e-04 1.29387883e-01
  1.00000000

<ipython-input-10-1391b4c23467>:76: RuntimeWarning: invalid value encountered in double_scalars
  prec[0][i] = max_element[i]/row_sum[i]
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: divide by zero encountered in true_divide
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: invalid value encountered in multiply
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))


clusters at k= 23 :
[13 10 18 ... 18 18 18]
23
Unique test cluster:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22]
[10 10 10 ... 10 10 10]
@K =  23
The count array size: (23, 36)
------------------------------------------------------------------------------
Conditional Entropy
[[0.00516093 0.         0.00533809 0.         0.04931501 0.06346986
  0.0304051  0.01228794 0.08632116 0.02640957 0.40538293 0.07080026
  0.         0.00418374 0.         0.34393573 0.         0.
  0.00678262 0.         0.         0.01341123 0.        ]]
Condition Entropy =  0.15959363379137162
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[0.99860608 1.         0.99833887 1.         0.97687458 0.96666667
  0.98685228 0.99559471 0.95591647 0.98894161 0.60519836 0.96153846
  1.         0.99874574 1.         0.64040284 1.         1.
  0.99823074 1.         0.         0.995671   1.        ]]
Total Precision =  0.8572528224426956


<ipython-input-10-1391b4c23467>:76: RuntimeWarning: invalid value encountered in double_scalars
  prec[0][i] = max_element[i]/row_sum[i]
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: divide by zero encountered in true_divide
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: invalid value encountered in multiply
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))


clusters at k= 31 :
[29 20 19 ... 19 19 19]
31
Unique test cluster:
[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[17 17 17 ... 17 17 17]
@K =  31
The count array size: (31, 36)
------------------------------------------------------------------------------
Conditional Entropy
[[0.27237293 0.22656329 0.         0.         0.0225676  0.02531595
  0.03102711 0.07293722 0.         0.01132546 0.10914441 0.01393092
  0.01664723 0.         0.00291286 0.00650659 0.07080026 0.29923643
  0.         0.00644717 0.07079127 0.27164745 0.31933777 0.
  0.02112404 0.         0.         0.         0.01421041 0.0053915
  0.00462994]]
Condition Entropy =  0.061087919049041164
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[0.67961165 0.78409091 0.         1.         0.99203187 0.9894988
  0.98723024 0.96       1.         0.996      0.9539715  0.99547511
  0.99442897 1.         0.9991715  0.9982

<ipython-input-10-1391b4c23467>:76: RuntimeWarning: invalid value encountered in double_scalars
  prec[0][i] = max_element[i]/row_sum[i]
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: divide by zero encountered in true_divide
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: invalid value encountered in multiply
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))


clusters at k= 45 :
[34  6 44 ... 44 44 44]
45
Unique test cluster:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 43 44]
[37 37 37 ... 37 37 37]
@K =  45
The count array size: (45, 36)
------------------------------------------------------------------------------
Conditional Entropy
[[2.39997061e-02 1.13871607e-02 1.56636327e-01 1.89423881e-04
  2.73388924e-01 6.28225494e-03 7.88028687e-02 0.00000000e+00
  0.00000000e+00 9.64762119e-03 0.00000000e+00 9.93118519e-03
  7.89635453e-02 0.00000000e+00 0.00000000e+00 1.11073801e-01
  0.00000000e+00 0.00000000e+00 2.81615932e-02 2.99232910e-01
  7.89386682e-02 1.78111254e-01 6.26925948e-03 1.26440425e-01
  0.00000000e+00 5.31403166e-03 1.44005066e-02 0.00000000e+00
  1.24212978e-01 1.38502341e-02 3.19337771e-01 7.43060556e-03
  3.97875610e-03 0.00000000e+00 4.69943472e-03 5.07841837e-03
  0.00000000e+00 3.11322666e-01 2.92285253e-01 0.00000000e+00
  0.00000000e+

<ipython-input-10-1391b4c23467>:76: RuntimeWarning: invalid value encountered in double_scalars
  prec[0][i] = max_element[i]/row_sum[i]
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: divide by zero encountered in true_divide
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
<ipython-input-10-1391b4c23467>:95: RuntimeWarning: invalid value encountered in multiply
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))


**Observation:** increasing the value of k, conditional entropy decreases but total precision increases.

In [ ]:
def evaluate2(clusters,testy): 
    ## cluster the testing set
    nu_clusters = len(np.unique(clusters))
    rows=len(clusters)


    d=testy  ##truth array
    t=clusters ##output array

    t_unique,t_count = np.unique(t,return_counts=True)
    d_unique,d_count = np.unique(d,return_counts=True)
    

    clus_row = nu_clusters
    clus_col = np.max(testy)+1
    print("@K = ",clus_row)
    count = np.zeros([clus_row,clus_col])
    ## count the number of different data in the clusters
    for i in range(len(t)):
       count[t[i]][d[i]] = count[t[i]][d[i]] +1    ## rows: output clusters (k), columns: testing clusters (40)
    row_sum= np.sum(count,axis=1) ## the sum of data in each cluster
    column_sum= np.sum(count,axis=0) ## the sum of data in different group of the test data
    total_row_sum = np.sum(row_sum) ## the total number of test data

    htc = np.zeros([1,clus_row])
    print("The count array size:", count.shape)


    ##Conditional Entropy
    print("------------------------------------------------------------------------------")
    print("Conditional Entropy")
    for i in range(clus_row):
      for j in range(clus_col):
        ## calculate H(T/Ci)
        if (count[i][j]):
          htc[0][i] = htc[0][i] - ( count[i][j]/row_sum[i] * math.log(count[i][j]/row_sum[i],10) )
    print(htc)
    htc_total = 0
    for i in range(clus_row):
      ## calculate the total entropy
      htc_total = htc_total + ( row_sum[i]/total_row_sum * htc[0][i] )
    print("Condition Entropy = ", htc_total)



    ##Precision and Recall
    print("------------------------------------------------------------------------------")
    print("Precision and Recall")
    max_element = np.max(count,axis=1) ## choose the majority element
    index_sum = np.zeros([1,len(max_element)])
    ## find the index of the major element in each cluster
    for i in range(len(max_element)):
      temp = np.argwhere(count == max_element[i])
      for j in temp:
        if (j[0] == i):
          index_sum[0][i] = column_sum[j[1]]

    prec = np.zeros([1,len(max_element)])
    total_prec=0 
    total_rec=0 
    rec = np.zeros([1,len(max_element)])

    for i in range(len(max_element)):
      ## calculate the precision of the cluster and the total precision
      prec[0][i] = max_element[i]/row_sum[i]
      prec[np.isnan(prec)] = 0
      total_prec = total_prec + (row_sum[i]/rows)*prec[0][i]
      ## calculate the recall of the cluster and the total recall
      rec[0][i] = max_element[i]/index_sum[0][i]      
      total_rec = total_rec + (row_sum[i]/rows)*rec[0][i]

    print("Precision: ")
    print(prec)
    print("Total Precision = ",total_prec)
  
    print("Recall:")
    print(rec)
    print("Total Recall = ",total_rec)
    

    ##F-score
    print("------------------------------------------------------------------------------")
    print("F-score")
    f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
    print("F-cluster: ")
    f_cluster[np.isnan(f_cluster)] = 0
    print(f_cluster)
    f_measure = np.sum(f_cluster,axis=1) * 1/clus_row
    print("F-score: ")
    f_measure[np.isnan(f_measure)] = 0
    print(f_measure)  

In [ ]:
def Similarity_knn(data,k,neigh):
    ## find the nearest k neighbours
    knn=NearestNeighbors(n_neighbors=neigh)
    knn.fit(data)
    #Compute the (weighted) graph of k-Neighbors for points in data.
    sim_matrix = knn.kneighbors_graph(data, mode='connectivity').toarray() 
    # compute delta matrix( sum of internal & external weights)
    delta_matrix=np.diag(np.sum(sim_matrix,axis=1))
    # get normalized asymmetric laplacian matrix
    l=delta_matrix-sim_matrix
    la=np.dot(np.linalg.inv(delta_matrix),l)
    #get eigenvalues& eigenvectors
    eigenvalues,eigenvectors=np.linalg.eig(la)
    # sort eigenvalues&eigenvectors and take number of eigenvectors equal to number of clusters     
    idx=eigenvalues.argsort()[:k]
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:,idx]
    # normalize eigenvectors
    rows_norm=np.linalg.norm(eigenvectors,axis=1) 
    vectors=np.real(np.transpose((np.transpose(eigenvectors)/rows_norm)))
    return eigenvalues,vectors

In [ ]:
# split total data to 0.00025 for train and 0.99975 for test   
split_train, split_test, splity_train, splity_test = train_test_split(xtrain_total, ytrain_total, test_size=0.99975, random_state=42,stratify=ytrain_total)
# apply normailzed cut algorithm for train
uniq = len(splity_train[41].unique())
values,norm_vectors=Similarity_knn(split_train,uniq,5)
vec = pd.DataFrame(norm_vectors)
new_centroids,clusters1 = kmeans(vec,uniq)
print("Ncut for 5-NN: ")
print(clusters1)
print(len(np.unique(clusters1)))

#apply kmeans algorithm for train
new_centroids2,clusters2 = kmeans(split_train,uniq)
print("kmeans for k=23: ")
print(clusters2)
print(len(np.unique(clusters2)))
split_test = split_test.to_numpy()
splity_test = splity_test.to_numpy()


Ncut for 5-NN: 
[3 0 3 ... 6 3 0]
7
kmeans for k=23: 
[5 6 6 ... 3 3 6]
7


In [ ]:
## evaluation of the output of the kmeans
splity_train_array = splity_train.to_numpy()
evaluate2(clusters2,splity_train_array)

@K =  7
The count array size: (7, 28)
------------------------------------------------------------------------------
Conditional Entropy
[[0.         0.         0.         0.34042111 0.         0.
  0.05500638]]
Condition Entropy =  0.14981398094105702
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[1.         1.         1.         0.63507109 1.         1.
  0.97229917]]
Total Precision =  0.857843137254902
Recall:
[[0.03703704 0.00411523 0.0617284  1.         0.02880658 0.19753086
  1.        ]]
Total Recall =  0.9435837435111218
------------------------------------------------------------------------------
F-score
F-cluster: 
[[0.07142857 0.00819672 0.11627907 0.77681159 0.056      0.32989691
  0.98595506]]
F-score: 
[0.33493827]


In [ ]:
## evaluation of the output of spectral clustering
vec_array = vec.to_numpy()
evaluate2(clusters1,splity_train_array)

@K =  7
The count array size: (7, 28)
------------------------------------------------------------------------------
Conditional Entropy
[[0.17330639 0.40966017 0.34709783 0.49870017 0.40536782 0.24640874
  0.24311863]]
Condition Entropy =  0.2869486810938034
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[0.89417989 0.69811321 0.73636364 0.41991342 0.53333333 0.78873239
  0.75229358]]
Total Precision =  0.7459150326797385
Recall:
[[0.72222222 0.2761194  0.30223881 0.13817664 0.05970149 0.07977208
  0.33744856]]
Total Recall =  0.44785170280718145
------------------------------------------------------------------------------
F-score
F-cluster: 
[[0.79905437 0.39572193 0.42857143 0.2079314  0.10738255 0.14489004
  0.46590909]]
F-score: 
[0.36420869]


###There is 2 major parameters for DBSCAN clustering.
1-Epsilon
This is the radius of the circle that we must draw around our pointing focus.

2-Minimum number of points
This is the number of points that we want in the neighbourhood of our point in focus (within the circle).

**DBSCAN** checks for clusters by checking the ε-neighborhood of every point in the database. If the ε-neighborhood of a point p contains more than MinPts, a new cluster with p as a core element is produced. DBSCAN iteratively assemble precisely density-reachable objects from these essential element, which can include the merge of a few density-reachable clusters. The process eliminates when no new point can be added to any cluster.

In [ ]:
#split_train, split_test, splity_train, splity_test = train_test_split(xtrain_total, ytrain_total, test_size=0.99975, random_state=42,stratify=ytrain_total)

#function to get the neighbours of a point
#points lying inside the circle of radius = epsilon
def insideCircle(D, p, epsilon):
  neighbors = []
  for pn in range(len(D)):
    # If the distance is within the radius epsilon, add it to the neighbors list.
    if np.linalg.norm(D[p] - D[pn]) < epsilon:
      neighbors.append(pn)          
  return neighbors

#to get neighbours of neighbours:
def expandCluster(D, labels, p, neighPoints, Cluster_id, epsilon, min_points):
  labels[p] = Cluster_id 
  i = 0
  while i < len(neighPoints):    
      # Get the next point.        
      pn = neighPoints[i]
      if labels[pn] == -1: #noise
          labels[pn] = Cluster_id
      elif labels[pn] == 0: #not visited before
          labels[pn] = Cluster_id
          # Find the neighbors of each pn:
          PnNeighborPts = insideCircle(D, pn, epsilon)
          if len(PnNeighborPts) >= min_points: #pn is not noise
              neighPoints = neighPoints + PnNeighborPts
      i += 1        
  
    # We've finished growing cluster C!

D = split_train.to_numpy()
labels = [0]*len(D)  
epsilon = 50
min_points = 35
Cluster_id = 0 #default
for p in range(len(D)):
  if(labels[p]==0):
    neighPoints = insideCircle(D, p, epsilon)
    if len(neighPoints) < min_points:
      labels[p] = -1
    else:
      Cluster_id += 1 
      expandCluster(D, labels, p, neighPoints, Cluster_id, epsilon, min_points)
print(labels)

[-1, 1, 2, 1, 1, -1, 1, 3, -1, 1, -1, 1, -1, 1, -1, 2, 1, -1, 3, 1, 1, -1, 2, 1, 3, 2, 3, 1, 2, 1, 2, 3, -1, 1, 1, 1, 3, 2, 3, 1, 1, 1, 1, -1, -1, 1, -1, 1, 3, 1, -1, -1, -1, 2, 1, 1, 3, 3, 1, 1, 1, -1, 1, 1, 2, 1, 1, 1, 1, 2, 1, -1, 1, 3, 3, 1, 1, 2, 1, 3, 3, 1, 1, 1, 2, 1, 2, 3, 1, -1, 3, 1, 1, -1, 3, -1, 3, 1, 3, 3, 1, 1, 2, 1, 3, 1, 3, 2, 1, 3, 3, 1, 1, 1, 1, -1, 3, 3, -1, -1, 2, 3, 1, 1, -1, 2, -1, -1, 1, 2, 3, -1, 1, -1, -1, 1, 3, 3, 3, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 3, 2, 1, -1, 1, 1, 1, 2, 1, -1, 1, 1, 1, 1, -1, 1, -1, 2, 2, 1, -1, -1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 1, 1, -1, 3, 3, 1, 1, 1, -1, -1, 3, 1, 3, 1, -1, 1, 2, 1, 1, 1, 1, 3, 2, -1, 1, 2, -1, 1, 3, 1, 3, 3, 1, 1, 1, -1, 1, 3, 1, 3, 1, 1, 1, 1, -1, -1, 1, 3, -1, 1, 1, 1, -1, 1, -1, -1, 3, 1, 3, 1, 1, 3, 3, 3, 1, 1, 1, 1, -1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, -1, -1, -1, -1, -1, 3, 3, 1, 1, -1, -1, 3, 2, 1, -1, -1, -1, 1, 3, 1, 1, 1, -1, 3, 3, 3, 3, -1, 2, 1, 3, -1, 1, 1, 1, 1, -1, -1, 1, 

In [ ]:
labels_array = np.asarray(labels)
evaluate2(labels_array,splity_train_array)

@K =  4
The count array size: (4, 28)
------------------------------------------------------------------------------
Conditional Entropy
[[0.         0.         0.         0.36369305]]
Condition Entropy =  0.1559957955443082
------------------------------------------------------------------------------
Precision and Recall
Precision: 
[[0.         1.         1.         0.51047619]]
Total Precision =  0.7900326797385621
Recall:
[[0.         0.79344729 0.2022792  1.        ]]
Total Recall =  0.8134589780831611
------------------------------------------------------------------------------
F-score
F-cluster: 
[[0.         0.88482923 0.33649289 0.67591425]]
F-score: 
[0.47430909]


<ipython-input-12-95e9cc1c8e8d>:65: RuntimeWarning: invalid value encountered in double_scalars
  prec[0][i] = max_element[i]/row_sum[i]
<ipython-input-12-95e9cc1c8e8d>:84: RuntimeWarning: divide by zero encountered in true_divide
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))
<ipython-input-12-95e9cc1c8e8d>:84: RuntimeWarning: invalid value encountered in multiply
  f_cluster = 2 * np.multiply ( np.multiply( prec , rec) , 1/(prec + rec))


In [ ]:
!jupyter nbconvert --to html /content/lab2.ipynb

[NbConvertApp] Converting notebook /content/lab2.ipynb to html
[NbConvertApp] Writing 702202 bytes to /content/lab2.html
